### ISSUE TITLE
Cannot find input file generation method

### ISSUE THREAD

**Issue by MichaelAbel1** [luo-group/MODIFY#4]
Hello, and thank you for your outstanding work.
May I ask how the data under the data file are obtained, can you add the generation method, such as GB1_zero_raw.csv, GB1_structure.csv and other files, I can't find the method or code to generate these files
Looking forward to your reply！

**Comment by MichaelAbel1** [comment]
I'm sorry, I didn't read the code carefully.

**Comment by kerrding** [comment]
Hi,

Thank you so much for your precious support of our work!

For the data files:

- `GB1_zero_raw.csv`: This file contains the raw zero-shot predictions for five zero-shot protein fitness predictors. An example of the computation can be found in `notebooks/zero.ipynb`.
- `GB1_structure.csv`: This file contains the structure-based scores from ESMFold and FoldX. Example commands can be found in section `3. Structure-based filtering` of the README file.

Please let us know if you have further questions regarding the implementation of MODIFY's constituent models. Thanks again for your support!

Best,
Kerr
